[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__"]
defineConstant = { DEBUG = true }

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.12.4"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = ".", extraPaths = ["tests/", "src/" ]},
]

[tool.pytest.ini_options]
pythonpath = "src"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "git: test send and receives from git",
]
